# hugo.toml

# Configuración básica del sitio
baseURL = "https://SuenaLaWeb.github.io/suena-la-web/" # CONFIRMADO Y LISTO!
languageCode = "es-ve"                                # Código de idioma del sitio
title = "Suena La Web"                             # Título principal del sitio web

# ¡NUEVA UBICACIÓN PARA LAS OPCIONES DE URL!
canonifyURLs = true       # Genera URLs absolutas completas usando baseURL
relativeURLs = false      # Desactivado, ya que canonifyURLs es true
uglyURLs = false          # Mantiene URLs limpias (sin .html al final)
disablePathToLower = true # Previene que Hugo convierta rutas a minúsculas

# Opciones de paginación (cuántos elementos por página, ej. en listas de noticias)
paginate = 10                                         # Muestra 10 elementos por página por defecto

# Parámetros globales que puedes usar en tus plantillas
[params]
  description = "Noticias y Música de Venezuela y el mundo. Suena La Web VE." # Descripción meta general
  author = "Noticias y Música"                          # Autor del sitio

# Taxonomías personalizadas (categorías, tags, etc.)
[taxonomies]
  categoria = "categorias"                            # Define 'categorias' como una taxonomía para tus contenidos

# Configuración del proceso de construcción de Hugo
[build]
  [build.processing.css.postcss]
    binary = "/mnt/e/suena_la_web/suena-la-web/node_modules/.bin/postcss"

# Configuración de los tipos de salida para diferentes secciones del sitio
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]