# hugo.toml
baseURL = "https://SuenaLaWeb.github.io/suena-la-web/"
languageCode = "es-ve"
title = "Suena La Web VE"
canonifyURLs = false
relativeURLs = true
uglyURLs = false
disablePathToLower = true
paginate = 10
[params]
  description = "Noticias y Música de Venezuela y el mundo. Suena La Web VE."
  author = "Suena La Web VE"
[taxonomies]
  categoria = "categorias"
[build]
  [build.processing.css.postcss]
    binary = "/mnt/e/suena_la_web/suena-la-web/node_modules/.bin/postcss"
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
[production]
  baseURL = "https://SuenaLaWeb.github.io/suena-la-web/"