baseURL = 'https://marvelous-custard-82f0a5.netlify.app/'
languageCode = 'en-us' # O 'es-ve'
title = 'Suena La Web - Noticias y Musica'
theme = "PaperMod" # <--- Confirma que es "PaperMod" (con P y M mayúsculas)

[taxonomies]
  categoria = "categorias" # Esto es correcto para tus posts