baseURL = 'https://marvelous-custard-82f0a5.netlify.app/'
languageCode = 'en-us'
title = 'Suena La Web - Noticias y Musica'

[taxonomies]
  categoria = "categorias"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]