# hugo.toml

# Configuración básica del sitio (para desarrollo local)
# ¡SIMPLIFICADO! Esto es la URL que Hugo Server mostrará.
baseURL = "/" # <--- ¡CAMBIO AQUÍ! La baseURL principal es solo la raíz.
languageCode = "es-ve"
title = "Suena La Web VE"

# Configuración de URLs (¡ESTO ES CLAVE para GitHub Pages en subdirectorio!)
# relativeURLs = true: para que | relURL funcione correctamente.
# canonifyURLs = false: para que Hugo no fuerce URLs absolutas completas sin el pathPrefix.
relativeURLs = true
canonifyURLs = false
uglyURLs = false
disablePathToLower = true

# Opciones de paginación
paginate = 10

# Parámetros globales
[params]
  description = "Noticias y Música de Venezuela y el mundo. Suena La Web VE."
  author = "Suena La Web VE"
  # Parámetro específico para GitHub Pages. ¡MUY IMPORTANTE!
  # Debe ser el nombre de tu repositorio, con '/' al principio.
  pathPrefix = "/suena-la-web" # <--- ¡AQUÍ VA EL NOMBRE DE TU REPOSITORIO CON '/' AL PRINCIPIO!

# Taxonomías
[taxonomies]
  categoria = "categorias"

# Configuración del proceso de construcción de Hugo
[build]
  [build.processing.css.postcss]
    binary = "/mnt/e/suena_la_web/suena-la-web/node_modules/.bin/postcss"

# Configuración de los tipos de salida
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# *** SECCIÓN IMPORTANTE PARA DESPLIEGUE A PRODUCCIÓN ***
# Define la baseURL específica para el entorno de producción (GitHub Pages).
# Hugo usará esta sección cuando se compile con `--environment production`.
[production]
  # ¡IMPORTANTE! Aquí la baseURL es la URL COMPLETA DEL DOMINIO RAÍZ de GitHub Pages.
  # PERO el pathPrefix de params se USARÁ para los assets.
  baseURL = "https://SuenaLaWeb.github.io/"