# netlify.toml

# Configuración principal de la construcción del sitio
[build]
  command = "npm install && hugo --minify"
  publish = "public"

# Variables de entorno específicas para el proceso de construcción en Netlify.
[build.environment]
  # ¡CORRECCIÓN CRUCIAL AQUÍ! DEBE COINCIDIR CON TU VERSIÓN DE HUGO EN WSL.
  HUGO_VERSION = "0.123.7" # <--- ¡Cambiado de 0.131.0 a 0.123.7!

  # Asegúrate de que NODE_VERSION coincida con tu 'node -v' en WSL (ej. "20" o "22")
  NODE_VERSION = "20" # Si tu 'node -v' es v22.x.x, usa "22" aquí.

  PATH = "$PATH:./node_modules/.bin" 
  
  # Si la línea anterior no funciona por alguna razón, puedes intentar esta alternativa:
  # NPM_BIN_PATH = "./node_modules/.bin"
  # Pero la configuración de PATH suele ser más universal.

# Contextos de despliegue (opcional, pero buena práctica)
# Permiten tener diferentes configuraciones para producción, previsualizaciones de despliegue, etc.
# Esto asegura que Hugo sepa el entorno
# [context.production]
#   environment = { HUGO_ENV = "production" }
#
# [context.deploy-preview]
#   environment = { HUGO_ENV = "development" }
#
# [context.branch-deploy]
#   environment = { HUGO_ENV = "development" }